namespace queensblood;

public static class Cards
{
    public static Card? At(int index)
    {
        if (index < 0 || index >= cards.Length) return null;
        return cards[index]();
    }

    public static Func<Card>[] CardsToAdd(int cardAddValue)
    {
        return minions.ElementAtOrDefault(cardAddValue) ?? [];
    }

    public static Func<Card>[] CardsToSpawn(int cardSpawnValue)
    {
        return minions.ElementAtOrDefault(cardSpawnValue) ?? [];
    }

    public static int Count => cards.Length;

    public static IEnumerable<Card> All => cards.Select(c => c());

    private static readonly Func<Card>[] cards = [
        () => new("Security Officer", 1, 1,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)]),
        () => new("Riot Trooper", 2, 3,
                    [new(-2, 0), new(-1, 0), new(0, 1), new(1, 0), new(2, 0)]),
        () => new("Grenadier", 2, 1,
                    abilityPositions: [new(0, 2)],
                    played: new(Effect.Enfeeble, CardRelation.Enemy, 4),
                    description: "When played, lower the power of enemy cards on affected tiles by 4."),
        () => new("J-Unit Sweeper", 2, 2,
                    [new(-1, 0), new(-1, 1), new(1, 0), new(1,1)],
                    imageOffsets: new(-15)),
        () => new("Queen Bee", 1, 1,
                    [new(-2, 0), new(2, 0)]),
        () => new("Toxirat", 2, 2,
                    [new(1, 0), new(1, 1)],
                    [new(1,1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 3),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 3."),
        () => new("Levikron", 1, 2,
                    [new(0, 1), new(1, 0)]),
        () => new("Grasslands Wolf", 1, 2,
                    [new(-1, 0), new(0, 1)]),
        () => new("Mu", 2, 1,
                    [new(-1, 1), new(0, 1)],
                    [new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 1),
                    description: "Raise the power of allied cards on affected tiles by 1 while this card is in play."),
        () => new("Mandragora", 1, 1,
                    [new(0, 1), new(1, 0)],
                    played: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.MandragoraMinion),
                    description: "When played, add Mandragora Minion to your hand."),
        () => new("Elphadunk", 2, 4,
                    [new(-1, 0), new(0, 1), new(1, 0)]),
        () => new("Cactuar", 1, 1,
                    [new(0, 1), new(1, 0)],
                    [new(2, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 3),
                    description: "Raise the power of allied cards on affected tiles by 3 while this card is in play."),
        () => new("Crystalline Crab", 1, 1,
                    [new(-1, 0), new(0, -1), new(0, 1)],
                    [new(-1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play."),
        () => new("Quetzalcoatl", 2, 3,
                    [new(-2, 0), new(-1, 1), new(1, 1), new(2, 0)],
                    fieldImageOffsets: new(10)),
        () => new("Zu", 2, 2,
                    [new(-1, -1), new(-1, 1), new(-1, 1), new(1, 1)]),
        () => new("Devil Rider", 2, 4,
                    [new(-1, -2), new(0, -2), new(0, -1), new(1, -2)]),
        () => new("Screamer", 3, 1,
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)]),
        () => new("Flan", 1, 2,
                    [new(-1, -1), new(0, -1), new(1, -1)]),
        () => new("Crawler", 1, 2,
                    [new(-1, -1), new(-1, 0), new(1, -1), new(1, 0)]),
        () => new("Archdragon", 1, 3,
                    [new(-1, -1), new(0, 1), new(1, -1)],
                    [new(0, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Enemy, 3),
                    description: "When played, lower the power of enemy cards on affected tiles by 3.",
                    imageOffsets: new(0, -20),
                    fieldImageOffsets: new(10)),
        () => new("Ogre", 2, 5,
                    [new(-2, 0), new(-2, 1), new(2, 0), new(2, 1)]),
        () => new("Deathwheel", 1, 1,
                    abilityPositions: [new(-2, 2), new(2, 2)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 3),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 3."),
        () => new("Fleetwing", 1, 3,
                    [new(-2, -2), new(-1, -1), new(1, -1), new(2, -2)]),
        () => new("Zemzelett", 2, 1,
                    [new(-1, 0), new(1, 0), new(1, 1)],
                    [new(0, -1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 3),
                    description: "Raise the power of allied cards on affected tiles by 3 while this card is in play."),
        () => new("Ignilisk", 1, 1,
                    [new(0, 1), new(2, 0)],
                    [new(0, 1), new(2, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play."),
        () => new("Capparwire", 1, 3,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    [new(-1, 0), new(1, 0)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 1),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 1.",
                    imageOffsets: new(YOffset: -10),
                    fieldImageOffsets: new(4)),
        () => new("Mindflayer", 2, 1,
                    [new(-1, 0), new(-1, 1), new(1, 0)],
                    [new(-1, 0), new(-1, 1), new(1, 0), new(1, 1)],
                    inPlay: new(Effect.Enfeeble, CardRelation.Both, 1),
                    description: "Lower the power of allied and enemy cards on affected tiles by 1 while this card is in play."),
        () => new("Scrutineye", 1, 1,
                    [new(-2, 0), new(2, 0)],
                    [new(-1, 0), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Both, 1),
                    description: "Raise the power of allied and enemy cards on affected tiles by 1 while this card is in play."),
        () => new("Hell Rider II", 3, 5,
                    [new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    [new(0, 1), new(1, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Enemy, 3),
                    description: "When played, lower the power of enemy cards on affected tiles by 3."),
        () => new("Flametrooper", 1, 3,
                    [new(-1, -1), new(-1, 0), new(0, -1), new(1, -1), new(1, 0)],
                    [new(-1, -1), new(0, -1), new(1, -1)],
                    destroyed: new(Effect.Enfeeble, CardRelation.Both, 3),
                    description: "When destroyed, lower the power of allied and enemy cards on affected tiles by 3."),
        () => new("Spearhawk", 1, 1,
                    [new(0, -1), new(0, 1), new(1, 0)],
                    [new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play."),
        () => new("Sea Devil", 3, 1,
                    [new(-1, 0), new(0, -1), new(0, 1)],
                    cardPlayed: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Power, CardRelation.Ally),
                    description: "When allied cards are played from hand, raise this card's power by 1."),
        () => new("Shoalopod", 2, 1,
                    [new(-1, 0), new(-1, 1), new(0, 1)],
                    [new(-1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 4),
                    description: "Raise the power of allied cards on affected tiles by 4 while this card is in play."),
        () => new("Crown Lance", 2, 2,
                    [new(1, 0), new(1, 1), new(2, 1)],
                    [new(1, 1), new(2, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 2),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 2."),
        () => new("Tonberry King", 2, 1,
                    [new(0, 1)],
                    cardDestroyed: new(Effect.Enhance, CardRelation.Self, 2, ValueType.Power, CardRelation.Ally),
                    description: "When allied cards are destroyed, raise this card's power by 2."),
        () => new("Sandhog Pie", 1, 1,
                    [new(-1, 0), new(0, 1)],
                    [new(-1, 0), new(0, 1)],
                    destroyed: new(Effect.Enhance, CardRelation.Ally, 3),
                    description: "When destroyed, raise the power of allied cards on affected tiles by 3."),
        () => new("Bloatfloat", 1, 1,
                    [new(0, 1), new(1, 0)],
                    [new(0, 2)],
                    destroyed: new(Effect.Enfeeble, CardRelation.Both, 4),
                    description: "When destroyed, lower the power of allied and enemy cards on affected tiles by 4."),
        () => new("Bagnadrana", 3, 2,
                    [new(0, 1), new(1, 1)],
                    cardPlayed: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Power, CardRelation.Enemy),
                    description: "When enemy cards are played from hand, raise this card's power by 1."),
        () => new("Cockatrice", 2, 3,
                    [new(0, 1)],
                    [new(0, 1)],
                    played: new(Effect.Destroy, CardRelation.Both),
                    description: "When played, destroy allied and enemy cards on affected tiles."),
        () => new("Heatseeker", 1, 1,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    destroyed: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.HeatseekerMinion),
                    description: "When destroyed, add Heatseeker Minion to your hand."),
        () => new("Bomb", 2, 2,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    destroyed: new(Effect.Enfeeble, CardRelation.Both, 4),
                    description: "When destroyed, lower the power of allied and enemy cards on affected tiles by 4.",
                    imageOffsets: new(YOffset: -15, Scale: 0.8f)),
        () => new("Thug", 2, 4,
                    [new(-2, 1), new(0, -1), new(0, 1), new(2, 1)]),
        () => new("Death Claw", 1, 2,
                    [new(-1, 0), new(0, 1)],
                    cardDestroyed: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Power, CardRelation.Enemy),
                    description: "When enemy cards are destroyed, raise this card's power by 1."),
        () => new("Landworm", 3, 5,
                    [new(0, 1), new(1, 0), new(1, 1)],
                    cardDestroyed: new(Effect.Enhance, CardRelation.Self, 2, ValueType.Power, CardRelation.Enemy),
                    description: "When enemy cards are destroyed, raise this card's power by 2."),
        () => new("Sandspitter", 2, 3,
                    [new(-2, 0), new(-2, 1), new(2, 0), new(2, 1)],
                    [new(-2, 0), new(-2, 1), new(2, 0), new(2, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 1),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 1.",
                    imageOffsets: new(0, -15)),
        () => new("Chimera", 2, 4,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 2, ValueType.Enfeebled, CardRelation.Enemy),
                    description: "Raise power by 2 for each enfeebled enemy card."),
        () => new("Joker", 2, 2,
                    [new(-2, 0), new(-2, 1), new(2, 0), new(2, 1)],
                    cardDestroyed: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Power, CardRelation.Both),
                    description: "When allied and enemy cards are destroyed, raise this card's power by 1."),
        () => new("Amphidex", 1, 2,
                    [new(-2, 0), new(0, 1)],
                    [new(-2, 0), new(-1, 0)],
                    enhanced: new(Effect.Enhance, CardRelation.Ally, 3),
                    description: "The first time this card is enhanced, raise the power of allied cards on affected tiles by 3."),
        () => new("Frightflower", 1, 1,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-2, -2), new(-2, 0), new(-2, 2), new(0, -2), new(0, 2), new(2, -2), new(2, 0), new(2, 2)],
                    destroyed: new(Effect.Enhance, CardRelation.Both, 2),
                    description: "When destroyed, raise the power of allied and enemy cards on affected tiles by 2."),
        () => new("Gagighandi", 2, 4,
                    [new(0, 1), new(1, 0), new(2, 0)],
                    [new(1, 1), new(2, 1)],
                    enhanced: new(Effect.Enfeeble, CardRelation.Enemy, 2),
                    description: "When first enhanced, lower the power of enemy cards on affected tiles by 2."),
        () => new("Insectoid Chimera", -1, 2,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    description: "Destroy an allied card and replace it.",
                    imageOffsets: new(0, -10)),
        () => new("Gigantoad", -1, 3,
                    [new(-1, 0), new(0, 1)],
                    description: "Destroy an allied card and replace it."),
        () => new("Maloceros", 3, 5,
                    [new(-2, 1), new(0, -1), new(0, 1), new(2, 1)],
                    laneWon: new(Effect.AddScore, CardRelation.Self, 10),
                    description: "When you win the lane, receive a score bonus of 10."),
        () => new("Grandhorn", -1, 3,
                    [new(0, 1), new(1, 0)],
                    description: "Destroy an allied card and replace it."),
        () => new("Great Malboro", 3, 3,
                    [new(-1, 1), new(0, 1), new(1, 1)],
                    [new(-1, 1), new(0, 1), new(1, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 6),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 6."),
        () => new("Grangalan", 3, 3,
                    [new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0)],
                    played: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.GrangalanJunior),
                    description: "When played, add Grangalan Junior to your hand."),
        () => new("Amalgam", 1, 1,
                    [new(0, -1), new(0, 1)],
                    destroyed: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.ResurrectedAmalgam),
                    description: "When destroyed, add Resurrected Amalgam to your hand."),
        () => new("Skeeskee", 1, 1,
                    [new(-1, 0), new(0, -1), new(0, 1)],
                    cardDestroyed: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Power, CardRelation.Ally),
                    description: "When allied cards are destroyed, raise this card's power by 1."),
        () => new("Griffon", -1, 1,
                    [new(-1, 0), new(0, 1)],
                    [new(-1, 1)],
                    played: new(Effect.Enhance, CardRelation.Ally, 0, ValueType.ReplacedPower),
                    description: "Replace an ally and raise the power of allied cards on affected tiles by the replaced ally's power."),
        () => new("Basilisk", 3, 2,
                    [new(-1, 1), new(1, -1), new(1, 1)],
                    [new(1, 1)],
                    played: new(Effect.Destroy, CardRelation.Enemy),
                    description: "When played, destroy enemy cards on affected tiles."),
        () => new("Reapertail", 1, 3,
                    [new(-1, 0), new(0, 1)],
                    [new(-2, 1), new(-1, 1)],
                    enfeebled: new(Effect.Enfeeble, CardRelation.Enemy, 2),
                    description: "When played, lower the power of enemy cards on affected tiles by 2."),
        () => new("Jabberwock", 2, 6,
                    [new(-1, 0), new(1, 0)],
                    [new(-1, -1), new(-1, 0), new(0, -1), new(1, -1), new(1, 0)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 1),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 1."),
        () => new("Desert Sahagin", 1, 3,
                    [new(0, 1), new(1, 0)],
                    [new(1, 0)],
                    enfeebled: new(Effect.Enhance, CardRelation.Ally, 4),
                    description: "When first enfeebled, raise the power of allied cards on affected tiles by 4."),
        () => new("Cavestalker", 2, 4,
                    [new(-2, 0), new(-1, 1), new(1, 1), new(2, 0)],
                    [new(-1, 1), new(0, 1), new(1, 1)],
                    enfeebled: new(Effect.Enfeeble, CardRelation.Enemy, 2),
                    description: "When first enfeebled, lower the power of enemy cards on affected tiles by 2."),
        () => new("Stone Golem", 1, 4,
                    abilityPositions: [new(0, 1)],
                    enhanced: new(Effect.Enfeeble, CardRelation.Enemy, 4),
                    description: "When first enhanced, lower the power of enemy cards on affected tiles by 4."),
        () => new("Two Face", 2, 3,
                    [new(-1, 0), new(1, 0)],
                    [new(-1, 0), new(1, 0)],
                    enhanced: new(Effect.Enhance, CardRelation.Ally, 4),
                    enfeebled: new(Effect.Enfeeble, CardRelation.Ally, 4),
                    description: "Enhanced: raise power of allied and enemy cards on affected tiles by 4. Enfeebled: lower their power by 4.",
                    imageOffsets: new(YOffset: -10, Scale: 0.7f)),
        () => new("Gi Specter", -1, 2,
                    [new(1, 0), new(1, 1)],
                    [new(1, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 0, ValueType.ReplacedPower),
                    description: "Replace an ally and lower the power of allied and enemy cards on affected tiles by the replaced ally's power."),
        () => new("Valron", 2, 3,
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 2, ValueType.Enfeebled, CardRelation.Ally),
                    description: "Raise power by 2 for each other enfeebled ally card."),
        () => new("Disgorgon", 2, 3,
                    [new(-1, 1), new(1, 1)],
                    rankBoost: 2,
                    description: "When played, raise position ranks by 2."),
        () => new("Dragon", 3, 5,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    played: new(Effect.Enfeeble, CardRelation.Enemy, 4),
                    description: "When played, lower the power of enemy cards on affected tiles by 4."),
        () => new("Twin Brain", 1, 1,
                    [new(-2, 0), new(2, 0)],
                    rankBoost: 2,
                    description: "When played, raise position ranks by 2."),
        () => new("Black Bat", 1, 2,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 1),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 1."),
        () => new("Bahba Velamyu", 1, 2,
                    [new(-1, 0), new(0, -1), new(0, 1)],
                    [new(-2, 1), new(-1, 1), new(0, 1), new(1, 1), new(2, 1)],
                    destroyed: new(Effect.Enfeeble, CardRelation.Enemy, 1),
                    description: "When destroyed, lower the power of enemy cards on affected tiles by 1."),
        () => new("Rictus", 1, 2,
                    [new(0, -1), new(0, 1), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Enfeebled, CardRelation.Both),
                    description: "Raise power by 1 for each other enfeebled allied and enemy card."),
        () => new("Adjudicator", 2, 1,
                    inPlay: new(Effect.Enhance, CardRelation.Self, 1, ValueType.EnhancedOrEnfeebled, CardRelation.Both),
                    description: "Raise power by 1 for each other enhanced or enfeebled allied and enemy card."),
        () => new("Yin & Yang", -1, 3,
                    [new(0, -1), new(0, 1)],
                    [new(-2, 0), new(2, 0)],
                    played: new(Effect.Enhance, CardRelation.Ally, 0, ValueType.ReplacedPower),
                    description: "Replace an ally and raise the power of allied cards on affected tiles by the replaced ally's power."),
        () => new("Diabolic Variant", -1, 2,
                    [new(0, -1), new(0, 1)],
                    [new(-1, 0), new(1, 0)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 0, ValueType.ReplacedPower),
                    description: "Replace an ally and lower the power of allied and enemy cards on affected tiles by the replaced ally's power."),
        () => new("Special Forces Operator", 1, 2,
                    [new(-2, 0), new(0, 1), new(2, 0)],
                    [new(-2, 0), new(2, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play."),
        () => new("2-C SOLDIER Operator", 2, 3,
                    [new(-2, 0), new(-2, 1), new(0, 1)],
                    [new(-2, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 3),
                    description: "Raise the power of allied cards on affected tiles by 3 while this card is in play."),
        () => new("Kelzmelzer", -1, 3,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    [new(-2, 1), new(2, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 0, ValueType.ReplacedPower),
                    description: "Replace an ally and lower the power of allied and enemy cards on affected tiles by the replaced ally's power."),
        () => new("Panthera Protector", 2, 3,
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, 1)],
                    [new(0, 1)],
                    enhanced: new(Effect.Enhance, CardRelation.Ally, 4),
                    description: "The first time this card is enhanced, raise the power of allied cards on affected tiles by 4."),
        () => new("Hecteyes", 1, 1,
                    abilityPositions: [new(-2, -2), new(-2, 0), new(-2, 2), new(0, -2), new(0, 2), new(2, -2), new(2, 0), new(2, 2)],
                    destroyed: new(Effect.Enhance, CardRelation.Ally, 3),
                    description: "When destroyed, raise the power of allied cards on affected tiles by 3."),
        () => new("Floating Death", 1, 1,
                    abilityPositions: [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 1),
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 1."),
        () => new("Ironclad", 3, 1,
                    [new(0, 1), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 3, ValueType.Enhanced, CardRelation.Enemy),
                    description: "Raise power by 3 for each enhanced enemy card."),
        () => new("Moss-Grown Adamantoise", 3, 4,
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(1, -1), new(1, 0), new(1, 1)],
                    rankBoost: 3,
                    description: "When played, raise position ranks by 3."),
        () => new Cloud(),
        () => new("Barret", 3, 4,
                    [new(0, 1), new(0, 2)],
                    [new(0, 2)],
                    played: new(Effect.Enfeeble, CardRelation.Enemy, 8),
                    legendary: true,
                    description: "When played, lower the power of enemy cards on affected tiles by 8."),
        () => new("Tifa", 1, 1,
                    [new(0, 1), new(1, 0), new(2, 0)],
                    laneWon: new(Effect.AddScore, CardRelation.Self, 5),
                    legendary: true,
                    description: "When you win the lane, receive a score bonus of 5."),
        () => new("Aerith", 2, 1,
                    [new(0, -1), new(0, 1)],
                    [new(0, -1), new(0, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 3),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 3 while this card is in play."),
        () => new("Red XIII", 1, 3,
                    [new(-1, 0), new(0, 1)],
                    [new(-2, -2), new(-2, 0), new(-2, 2), new(0, -2), new(0, 2), new(2, -2), new(2, 0), new(2, 2)],
                    enfeebled: new(Effect.Enfeeble, CardRelation.Enemy, 2),
                    legendary: true,
                    description: "When first enfeebled, lower the power of enemy cards on affected tiles by 2."),
        () => new("Yuffie", -1, 1,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 0, ValueType.ReplacedPower),
                    legendary: true,
                    description: "Replace an ally and lower the power of allied and enemy cards on affected tiles by the replaced ally's power."),
        () => new("Cait Sith", 1, 1,
                    [new(0, -1), new(0, 1), new(1, 0)],
                    played: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.Moogle),
                    legendary: true,
                    description: "When played, add Moogle to your hand."),
        () => new("Cid", 1, 2,
                    [new(-2, 0), new(0, 1)],
                    played: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.TinyBronco),
                    legendary: true,
                    description: "When played, add The Tiny Bronco to your hand."),
        () => new("Vincent", 1, 2,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    destroyed: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.GalianBeast),
                    legendary: true,
                    description: "When destroyed, add Galian Beast to your hand."),
        () => new("Ifrit", 3, 5,
                    [new(-1, 0), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 2, ValueType.Enhanced, CardRelation.Ally),
                    legendary: true,
                    description: "Raise power by 2 for each other enhanced ally card."),
        () => new("Shiva", 2, 4,
                    played: new(Effect.SpawnCards, CardRelation.Self, (int)CardSpawns.DiamondDust),
                    legendary: true,
                    description: "When played, spawn Diamond Dust of power 2, 4, and 6 in empty positions."),
        () => new("Ramuh", 3, 3,
                    [new(-2, -2), new(-2, 2), new(-1, -1), new(-1, 1), new(1, -1), new(1, 1), new(2, -2), new(2, 2)],
                    [new(-2, -2), new(-2, 2), new(-1, -1), new(-1, 1), new(1, -1), new(1, 1), new(2, -2), new(2, 2)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 3),
                    legendary: true,
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 3."),
        () => new("Titan", 2, 5,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    rankBoost: 2,
                    legendary: true,
                    description: "When played, raise position ranks by 2."),
        () => new("Kujata", 3, 6,
                    [new(-1, 1), new(0, -1), new(1, 1)],
                    [new(-1, 1), new(0, -1), new(1, 1)],
                    enhanced: new(Effect.Enfeeble, CardRelation.Enemy, 5),
                    legendary: true,
                    description: "When first enhanced, lower the power of enemy cards on affected tiles by 5."),
        () => new("Odin", 2, 3,
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 2, ValueType.Enhanced, CardRelation.Enemy),
                    legendary: true,
                    description: "Raise power by 2 for each enhanced enemy card."),
        () => new("Phoenix", 3, 4,
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    destroyed: new(Effect.Enhance, CardRelation.Ally, 5),
                    legendary: true,
                    description: "When destroyed, raise the power of allied cards on affected tiles by 5."),
        () => new("Leviathan", 2, 4,
                    [new(-2, 0), new(0, -2), new(0, 2), new(2, 0)],
                    [new(-2, -2), new(-2, 0), new(-2, 2), new(0, -2), new(0, 2), new(2, -2), new(2, 0), new(2, 2)],
                    inPlay: new(Effect.Enfeeble, CardRelation.Enemy, 3),
                    legendary: true,
                    description: "Lower the power of enemy cards on affected tiles by 3 while this card is in play.",
                    imageOffsets: new(YOffset: -10)),
        () => new("Alexander", 3, 4,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 3, ValueType.Enfeebled, CardRelation.Ally),
                    legendary: true,
                    description: "Raise power by 3 for each other enfeebled ally card."),
        () => new("Bahamut", 3, 5,
                    [new(-1, 0), new(0, -1), new(0, 1), new(0, 2), new(1, 0)],
                    [new(0, 1), new(0, 2)],
                    played: new(Effect.Enfeeble, CardRelation.Enemy, 5),
                    legendary: true,
                    description: "When played, lower the power of enemy cards on affected tiles by 5."),
        () => new("Bahamut Arisen", 3, 4,
                    played: new(Effect.SpawnCards, CardRelation.Self, (int)CardSpawns.Elemental),
                    legendary: true,
                    description: "When played, spawn Elementals - cards that enhance when destroyed - in your empty positions."),
        () => new("Gilgamesh", -1, 3,
                    abilityPositions: [new(-2, -2), new(-2, 2), new(2, -2), new(2, 2)],
                    played: new(Effect.Enhance, CardRelation.Both, 0, ValueType.ReplacedPower),
                    legendary: true,
                    description: "Replace an ally and raise the power of allied and enemy cards on affected tiles by the replaced ally's power."),
        () => new("Chocobo & Moogle", 1, 1,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Enhanced, CardRelation.Ally),
                    legendary: true,
                    description: "Raise power by 1 for each other enhanced ally card."),
        () => new("Fat Chocobo", 3, 5,
                    [new(-2, 0), new(-1, -1), new(-1, 1), new(0, -2), new(0, 2), new(1, -1), new(1, 1), new(2, 0)],
                    legendary: true,
                    description: "Creates a surfeit of positions around it when played."),
        () => new("Posh Chocobo", 1, 2,
                    [new(0, -1), new(0, 1)],
                    laneWon: new(Effect.AddScore, CardRelation.Self, 3),
                    legendary: true,
                    description: "When you win the lane, receive a score bonus of 3."),
        () => new("Moogle Trio", 2, 1,
                    [new(-1, 1), new(1, 1)],
                    played: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.MooglePair),
                    legendary: true,
                    description: "When played, add Moogle Mage and Moogle Bard to your hand."),
        () => new("Magic Pot", 3, 1,
                    abilityPositions: [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play."),
        () => new("Materia Guardian", 3, 5,
                    [new(-2, 0), new(-1, 0), new(0, 1), new(1, 0), new(2, 0)],
                    [new(-2, -2), new(-2, -1), new(-2, 1), new(-2, 2), new(2, -2), new(2, -1), new(2, 1), new(2, 2)],
                    enfeebled: new(Effect.Enfeeble, CardRelation.Enemy, 6),
                    legendary: true,
                    description: "When first enfeebled, lower the power of enemy cards on affected tiles by 6."),
        () => new("Midgardsormr", 3, 6,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    cardDestroyed: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Power, CardRelation.Both),
                    legendary: true,
                    description: "When allied and enemy cards are destroyed, raise this card's power by 1."),
        () => new("Mythril Golem", 3, 8,
                    [new(-1, 0), new(1, 0)],
                    legendary: true,
                    description: "Possesses a crystal-hard resolve and an overwhelming amount of power."),
        () => new("Terror of the Deep", 3, 2,
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    inPlay: new(Effect.Enfeeble, CardRelation.Both, 1),
                    legendary: true,
                    description: "Lower the power of allied and enemy cards on affected tiles by 1 while this card is in play."),
        () => new("Grasptropod", 3, 5,
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    [new(-2, -2), new(-2, 2), new(-1, -2), new(-1, 2), new(1, -2), new(1, 2), new(2, -2), new(2, 2)],
                    enhanced: new(Effect.Enfeeble, CardRelation.Both, 4),
                    legendary: true,
                    description: "When first enhanced, lower the power of allied and enemy cards on affected tiles by 4."),
        () => new("Custom Valkyrie", 3, 4,
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 4),
                    legendary: true,
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 4."),
        () => new("Gigatrice", 3, 4,
                    [new(-2, 0), new(-2, 1), new(-1, 0), new(1, 0), new(2, 0), new(2, 1)],
                    [new(-2, 1), new(2, 1)],
                    played: new(Effect.Destroy, CardRelation.Both),
                    legendary: true,
                    description: "When played, destroy allied and enemy cards on affected tiles."),
        () => new("Dyne", 3, 4,
                    [new(-2, 1), new(-1, 2), new(1, 2), new(2, 1)],
                    [new(-2, 1), new(-1, 2), new(1, 2), new(2, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 5),
                    legendary: true,
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 5."),
        () => new("Anuran Suppressor", 2, 2,
                    [new(0, 1), new(2, 0), new(2, 1)],
                    cardDestroyed: new(Effect.Enhance, CardRelation.Self, 2, ValueType.Power, CardRelation.Enemy),
                    legendary: true,
                    description: "When enemy cards are destroyed, raise this card's power by 2."),
        () => new("Specimen H1024", 3, 6,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-2, -2), new(-2, 0), new(-2, 2), new(0, -2), new(0, 2), new(2, -2), new(2, 0), new(2, 2)],
                    inPlay: new(Effect.Enhance, CardRelation.Both, 3),
                    legendary: true,
                    description: "Raise the power of allied and enemy cards on affected tiles by 3 while this card is in play."),
        () => new("Crimson Mare Mk. II", 3, 5,
                    [new(-1, 0), new(-1, 1), new(1, 0), new(1, 1)],
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    enfeebled: new(Effect.Enfeeble, CardRelation.Both, 5),
                    legendary: true,
                    description: "When first enfeebled, lower the power of allied and enemy cards on affected tiles by 5."),
        () => new("Gi Nattak", -1, 1,
                    [new(-1, 0), new(1, 0)],
                    [new(-1, 0), new(1, 0)],
                    played: new(Effect.Enhance, CardRelation.Ally, 0, ValueType.ReplacedPower),
                    legendary: true,
                    description: "Replace an ally and raise the power of allied cards on affected tiles by the replaced ally's power."),
        () => new("Forgotten Specimen", 3, 4,
                    [new(-2, 1), new(-1, 1)],
                    [new(2, -1), new(1, -1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 3),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 3 while this card is in play."),
        () => new("Don Corneo & Abzu", 2, 4,
                    played: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.CorneoPair),
                    legendary: true,
                    description: "When played, add both Cacneo and Donberry to your hand."),
        () => new("Red Dragon", 3, 6,
                    [new(-2, 0), new(-1, 1), new(0, 2), new(1, 1), new(2, 0)],
                    [new(-2, 0), new(-1, 1), new(0, 2), new(1, 1), new(2, 0)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 4),
                    legendary: true,
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 4."),
        () => new("Demon Gate", 3, 5,
                    [new(-1, -1), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 1)],
                    [new(-1, -1), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 1)],
                    destroyed: new(Effect.Enfeeble, CardRelation.Enemy, 9),
                    legendary: true,
                    description: "When destroyed, lower the power of enemy cards on affected tiles by 9."),
        () => new("Reno", 1, 2,
                    [new(0, 1), new(1, 0)],
                    [new(1, -1), new(2, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play."),
        () => new("Rude", 1, 2,
                    [new(-1, 0), new(0, 1)],
                    [new(-2, 0), new(-1, -1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play."),
        () => new("Elena", 1, 2,
                    [new(0, 1)],
                    [new(0, 1)],
                    enhanced: new(Effect.Enfeeble, CardRelation.Both, 99),
                    legendary: true,
                    description: "When first enhanced, lower the power of allied and enemy cards on affected tiles by 99."),
        () => new("Tseng", 1, 1,
                    [new(-1, 0), new(0, 1), new(1, 0)],
                    [new(0, 2)],
                    enhanced: new(Effect.Enhance, CardRelation.Ally, 4),
                    legendary: true,
                    description: "The first time this card is enhanced, raise the power of allied cards on affected tiles by 4."),
        () => new("Rufus", 2, 4,
                    [new(-2, -1), new(-2, 1), new(-1, -1), new(-1, 1), new(1, -1), new(1, 1), new(2, -1), new(2, 1)],
                    legendary: true,
                    description: "Creates an intimidatingly large number of positions around him when played."),
        () => new("Roche", 2, 6,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-2, -2), new(-2, 0), new(-2, 2), new(-1, -1), new(-1, 1), new(0, -2), new(0, 2), new(1, -1), new(1, 1), new(2, -2), new(2, 0), new(2, 2)],
                    played: new(Effect.Enfeeble, CardRelation.Ally, 1),
                    legendary: true,
                    description: "When played, lower the power of allied cards on affected tiles by 1."),
        () => new("J-Squad", 3, 2,
                    played: new(Effect.SpawnCards, CardRelation.Self, (int)CardSpawns.HypeJohnnys),
                    legendary: true,
                    description: "When played, spawn Hype Johnnys - cards that enhance while in play - in your empty positions."),
        () => new("Chocobo Jockey", 2, 2,
                    [new(0, 1)],
                    laneWon: new(Effect.AddScore, CardRelation.Self, 10),
                    legendary: true,
                    description: "When you win the lane, receive a score bonus of 10."),
        () => new("Space Ranger", 1, 2,
                    [new(-2, 0), new(-1, 0), new(0, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Enhanced, CardRelation.Enemy),
                    legendary: true,
                    description: "Raise power by 1 for each other enhanced enemy card."),
        () => new("Haunted Hotel", 1, 1,
                    [new(-1, 0), new(1, 0)],
                    [new(-1, 1), new(-1, 2), new(1, 1), new(1, 2)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play.",
                    imageOffsets: new(YOffset: -20)),
        () => new("Skywheel", 3, 2,
                    [new(-2, -1), new(-2, 1), new(-1, -2), new(-1, 2), new(1, -2), new(1, 2), new(2, -1), new(2, 1)],
                    legendary: true,
                    description: "Adds positions in the shape of a certain Gold Saucer attraction.",
                    imageOffsets: new(Scale: 1.2f)),
        () => new("Loveless", 1, 1,
                    abilityPositions: [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    played: new(Effect.Enhance, CardRelation.Both, 1),
                    legendary: true,
                    description: "When played, raise the power of allied and enemy cards on affected tiles by 1.",
                    imageOffsets: new(Scale: 1.4f)),
        () => new("Saucer Squad", 2, 3,
                    [new(-2, 1), new(-1, 0), new(0, 1), new(1, 0), new(2, 1)],
                    legendary: true,
                    description: "Makes use of its adorable nature to enliven the battlefield."),
        () => new("Dio", 3, 4,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 1, ValueType.Enhanced, CardRelation.Both),
                    legendary: true,
                    description: "Raise power by 1 for each other enhanced allied and enemy card."),
        () => new("Ultimate Party Animal", 1, 1,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    legendary: true,
                    description: "If this card is in play when the round ends, the loser of each lane's score is added to the victor's."),
        () => new("Sephiroth", 3, 4,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-1, 0), new(1, 0)],
                    played: new(Effect.Destroy, CardRelation.Enemy),
                    legendary: true,
                    description: "When played, destroy enemy cards on affected tiles."),
        () => new("Emerald Witch", 2, 2,
                    [new(-1, 0), new(0, -1), new(0, 1), new(1, 0)],
                    [new(-2, 0), new(-1, -1), new(-1, 1), new(0, -2), new(0, 2), new(1, -1), new(1, 1), new(2, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Both, 2),
                    legendary: true,
                    description: "Raise the power of allied and enemy cards on affected tiles by 2 while this card is in play."),
        () => new("Shadowblood Queen", 3, 3,
                    [new(-1, 0), new(-1, 1), new(1, 0), new(1, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Self, 3, ValueType.Enfeebled, CardRelation.Both),
                    legendary: true,
                    description: "Raise power by 3 for each other enfeebled allied and enemy card.",
                    imageOffsets: new(Scale: 1.2f)),
    ];

    private static readonly Func<Card>[][] minions = [
        [() => new("Mandragora Minion", 1, 1,
                    [new(-1, 0), new(0, 1)])],
        [() => new("Heatseeker Minion", 1, 1,
                    [new(-1, 0), new(0, 1), new(1, 0)])],
        [() => new("Grangalan Junior", 2, 2,
                    [new(-1, -1), new(-1, 1), new(1, -1), new(1, 1)],
                    played: new(Effect.AddCard, CardRelation.Self, (int)CardAdds.BabyGrangalan),
                    description: "When played, add Baby Grangalan to your hand.")],
        [() => new("Baby Grangalan", 1, 1,
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    destroyed: new(Effect.Enfeeble, CardRelation.Both, 5),
                    description: "When destroyed, lower the power of allied and enemy cards on affected tiles by 5.")],
        [() => new("Resurrected Amalgam", 1, 2,
                    [new(-1, 0), new(1, 0)],
                    [new(-1, 0), new(1, 0)],
                    inPlay: new(Effect.Enfeeble, CardRelation.Both, 2),
                    description: "Lower the power of allied and enemy cards on affected tiles by 2 while this card is in play.")],
        [() => new("Moogle", 2, 2,
                    [new(0, 1), new(1, 1)],
                    [new(-1, 0)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 3),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 3 while this card is in play.")],
        [() => new("The Tiny Bronco", 2, 2,
                    [new(0, 1), new(1, 0), new(2, 1)],
                    rankBoost: 2,
                    legendary: true,
                    description: "When played, raise position ranks by 2.")],
        [() => new("Galian Beast", 2, 4,
                    abilityPositions: [new(-2, -1), new(-2, 0), new(-2, 1), new(-1, -2), new(-1, 2), new(0, -2), new(0, 2), new(1, -2), new(1, 2), new(2, -1), new(2, 0), new(2, 1)],
                    played: new(Effect.Enfeeble, CardRelation.Both, 1),
                    legendary: true,
                    description: "When played, lower the power of allied and enemy cards on affected tiles by 1.")],
        [() => new("Moogle Mage", 1, 1,
                    [new(-2, 2)],
                    [new(-2, 2)],
                    played: new(Effect.Enfeeble, CardRelation.Enemy, 4),
                    legendary: true,
                    description: "When played, lower the power of enemy cards on affected tiles by 4."),
         () => new("Moogle Bard", 1, 1,
                    [new(0, 1), new(1, 0)],
                    [new(1, 1), new(2, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 2),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 2 while this card is in play.")],
        [() => new("Cacneo", 2, 2,
                    [new(-1, 1), new(0, 1), new(1, 1)],
                    [new(-2, 1), new(2, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Ally, 3),
                    legendary: true,
                    description: "Raise the power of allied cards on affected tiles by 3 while this card is in play."),
         () => new("Donberry", 2, 2,
                    [new(0, 1)],
                    [new(0, 1)],
                    played: new(Effect.Destroy, CardRelation.Enemy),
                    legendary: true,
                    description: "When played, destroy enemy cards on affected tiles.")],
    ];

    private static readonly Func<Card>[][] spawns = [
        [() => new("Diamond Dust", 0, 2),
         () => new("Diamond Dust", 0, 4),
         () => new("Diamond Dust", 0, 6)],
        [() => new("Elemental", 0, 1,
                    abilityPositions: [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    destroyed: new(Effect.Enhance, CardRelation.Both, 1),
                    legendary: true,
                    description: "When destroyed, raise the power of allied and enemy cards on affected tiles by 1.")],
        [() => new("Hype Johnnys I", 0, 3,
                    abilityPositions: [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Both, 1),
                    legendary: true,
                    description: "Raise the power of allied and enemy cards on affected tiles by 1 while this card is in play."),
         () => new("Hype Johnnys II", 0, 2,
                    abilityPositions: [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Both, 2),
                    legendary: true,
                    description: "Raise the power of allied and enemy cards on affected tiles by 2 while this card is in play."),
         () => new("Hype Johnnys III", 0, 1,
                    abilityPositions: [new(-1, -1), new(-1, 0), new(-1, 1), new(0, -1), new(0, 1), new(1, -1), new(1, 0), new(1, 1)],
                    inPlay: new(Effect.Enhance, CardRelation.Both, 4),
                    legendary: true,
                    description: "Raise the power of allied and enemy cards on affected tiles by 4 while this card is in play.")],
    ];

    private enum CardAdds
    {
        MandragoraMinion = 0,
        HeatseekerMinion = 1,
        GrangalanJunior = 2,
        BabyGrangalan = 3,
        ResurrectedAmalgam = 4,
        Moogle = 5,
        TinyBronco = 6,
        GalianBeast = 7,
        MooglePair = 8,
        CorneoPair = 9,
    }

    private enum CardSpawns
    {
        DiamondDust = 0,
        Elemental = 1,
        HypeJohnnys = 2,
    }
}
